export const buttons = {
  btn0: { value: 0, className: "btn--default", area: "btnCero" },
  btn1: { value: 1, className: "btn--default", area: "btnOne" },
  btn2: { value: 2, className: "btn--default", area: "btnTwo" },
  btn3: { value: 3, className: "btn--default", area: "btnThree" },
  btn4: { value: 4, className: "btn--default", area: "btnFour" },
  btn5: { value: 5, className: "btn--default", area: "btnFive" },
  btn6: { value: 6, className: "btn--default", area: "btnSix" },
  btn7: { value: 7, className: "btn--default", area: "btnSeven" },
  btn8: { value: 8, className: "btn--default", area: "btnEight" },
  btn9: { value: 9, className: "btn--default", area: "btnNine" },
  btnDel: { value: "delete", className: "btn--grey", area: "btnDel" },
  btnPlus: { value: "+", className: "btn--default", area: "btnPlus" },
  btnMinus: { value: "-", className: "btn--default", area: "btnMinus" },
  btnDivide: { value: "/", className: "btn--default", area: "btnDivide" },
  btnMult: { value: "*", className: "btn--default", area: "btnMult" },
  btnPeriod: { value: ".", className: "btn-default", area: "btnPeriod" },
  btnReset: { value: "reset", className: "btn--grey", area: "reset" },
  btnEqual: { value: "equal", className: "btn--red", area: "equal" },
};
